teslamotors/kafka-helmsman

.gitignore, kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/BUILD, kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/BaseCommand.java, kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/DumpCommand.java, kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/EnforceCommand.java, kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/Main.java, kafka_topic_enforcer/src/test/java/com/tesla/data/topic/enforcer/BUILD, kafka_topic_enforcer/src/test/java/com/tesla/data/topic/enforcer/CommandTest.java, kafka_topic_enforcer/src/test/java/com/tesla/data/topic/enforcer/EnforceCommandTest.java
Prior to this change, topic-enforcer would crash if an error is encountered
in one of the runs in continous mode. Thats not what we want, the expected
ux is to track the error but continue to be alive and maintain continous
enforcement.
To improve testing, this change refactors cli layers.
=> Fix kafka topic-enforcer crash in continous mode if an exception occurs

kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/Enforcer.java, kafka_topic_enforcer/src/test/java/com/tesla/data/topic/enforcer/BUILD, kafka_topic_enforcer/src/test/java/com/tesla/data/topic/enforcer/EnforcerTest.java
Prior to this change unsafe flag only affected topic deletion behavior, this
change ensures that we make the behavior consistent across all kinds of changes
(a) partition increase (b) config update (c) topic deletion
This change also improves logging, for instance if an unsafe drift was detected
while operating in safe mode -- enforcer wouldn't report it in the logs --
very bad ux. This change reports all drifts regardless of the operating mode.
=> Honor unsafe mode in partition increase & config update flow

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/ConsumerFreshness.java, kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/FreshnessMetrics.java
Useful for understanding when a cluster becomes misconfigured or unreachable (e.g. goes down)
=> Add metric to track when we get an exception on querying Kafka

kafka_certificates/src/main/java/com/tesla/data/certificates/keystore/BUILD, kafka_certificates/src/main/java/com/tesla/data/certificates/keystore/KafkaClientKeystores.java
So the library can be used outside of just a command-line tool
=> Making kafka_certificates lib and KafkaClientKeystores#writeStores public

kafka_certificates/src/main/java/com/tesla/data/certificates/keystore/KafkaClientKeystores.java, kafka_certificates/src/main/java/com/tesla/data/certificates/keystore/KeystoreConfig.java, kafka_certificates/src/test/java/com/tesla/data/certificates/keystore/KafkaClientKeystoresTest.java
Rather than making sure you pass in the right certificates to the input
streams, now you just pass in an instance of KeystoreConfig and it does
the right thing for you when creating the keystore or truststore. However,
also allows access to underlying methods to make the stores yourself, if
you prefer.
Also, adds support for reading the Issuing CA certificate from the CA Chain,
rather than having a separate certificate. This is a common way certificates
are handed out to clients, so also improves usability dramatically (rather
than messing with manually editing certs).
=> Keystore as-a-library usability improvements

kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/ConfiguredTopic.java, kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/DumpCommand.java, kafka_topic_enforcer/src/test/java/com/tesla/data/topic/enforcer/CommandTest.java
Tags are a list of (un-restricted) key value pairs that can be associated
with a topic through the enforcer config. They are purely cosmetic at
the moment and not serialized on the broker side -- i.e. a configured
topic de-serialized via admin API would be missing tags.
=> Add support for tagging a configured topic

kafka_roller/kafka_roller/tasks.py
Adding a counter of hosts, so you can see at a glance how many hosts in the restart
remain (helpful when you can't scroll back the terminal easily).
Also adds a timer of the restart for the host, useful when trying to predict remaining
time in teh restart and when tweaking configurations and trying to improve the MTTR.
=> Improve roller logging of progress

kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/ClusterTopics.java, kafka_topic_enforcer/src/test/java/com/tesla/data/topic/enforcer/BUILD, kafka_topic_enforcer/src/test/java/com/tesla/data/topic/enforcer/ClusterTopicsTest.java
Motivation:
Kafka topic enforcer accepts a config file that is tied to a cluster. This
means you could have N config files for N clusters. Generally, there is a lot of
overlap in these configs, for instance, production and staging configs only
differ in properties such as partition count, replication factor, etc.
It'd be operationally simple and less error-prone to reduce the number
of configs, this change is a step in that direction.
=> Add a utility class for parsing multi cluster topic config

kafka_enforcer_common/src/main/java/com/tesla/data/enforcer/BUILD, kafka_enforcer_common/src/main/java/com/tesla/data/enforcer/Enforcer.java, kafka_enforcer_common/src/test/java/com/tesla/data/enforcer/BUILD, kafka_enforcer_common/src/test/java/com/tesla/data/enforcer/Dummy.java, kafka_enforcer_common/src/test/java/com/tesla/data/enforcer/DummyEnforcer.java, kafka_enforcer_common/src/test/java/com/tesla/data/enforcer/EnforcerTest.java
This change extracts enforcement loop into a common lib & makes
it entity agnostic. This is prep work for acl enforcer, goal is
to re-use core pieces present in topic enforcer.
=> Abstract Enforcer in a re-usable library

kafka_enforcer_common/src/main/java/com/tesla/data/enforcer/BaseCommand.java, kafka_enforcer_common/src/main/java/com/tesla/data/enforcer/ClusterEntities.java, kafka_enforcer_common/src/main/java/com/tesla/data/enforcer/EnforceCommand.java, kafka_enforcer_common/src/test/java/com/tesla/data/enforcer/BUILD, kafka_enforcer_common/src/test/java/com/tesla/data/enforcer/BaseCommandTest.java, kafka_enforcer_common/src/test/java/com/tesla/data/enforcer/ClusterEntitiesTest.java, kafka_enforcer_common/src/test/java/com/tesla/data/enforcer/EnforceCommandTest.java
This change extracts few more abstractions into a common lib
& makes it entity agnostic. This is prep work for acl enforcer,
goal is to re-use core pieces present in topic enforcer.
=> Pull BaseCommand, EnforceCommand & ClusterEntities into common

kafka_enforcer_common/src/main/java/com/tesla/data/enforcer/BUILD
In a recent refactoring exercise the visibility was downgraded
=> Make BaseCommand public again

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/Burrow.java, kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/ConsumerFreshness.java, kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/FreshnessMetrics.java
This change adds a sanity check during burrow client initialization.
App will abort if it fails to detect a healthy burrow.
Also, it was noticed that some metrics were not being registered.
As a fix, this change moves metric registration inline as opposed
to a whitelist.
=> Do a basic health check on burrow during app initialization

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/ConsumerFreshness.java, kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/FreshnessMetrics.java
This provides us with a direct indicator to alert on, ex: last run was N hours ago
=> Add a metric to track last successful run timestamp per cluster

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/FreshnessMetrics.java
Variables are initialized before constructor executes and in constructor
we clear the registry, this was a bug which is being fixed in this change.
=> Move freshness metric variable initialization to constructor

.github/workflows/ci.yml, kafka_acl_enforcer/src/main/java/com/tesla/data/acl/AclEnforceCommand.java, kafka_acl_enforcer/src/main/java/com/tesla/data/acl/BUILD, kafka_acl_enforcer/src/main/java/com/tesla/data/acl/Main.java, kafka_enforcer_common/src/main/java/com/tesla/data/enforcer/BaseCommand.java
Allows external uses of ACL command, e.g for validation of ACL configs
=> Expose ACL enforcer command

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/ConsumerFreshness.java, kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/FreshnessMetrics.java, kafka_consumer_freshness_tracker/src/test/java/com/tesla/data/consumer/freshness/BUILD, kafka_consumer_freshness_tracker/src/test/java/com/tesla/data/consumer/freshness/ConsumerFreshnessTest.java
Allows tracker to ride over bad consumer groups, clusters, and/or burrow reads
=> Freshness tracker should tolerate runtime exceptions when checking status

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/ConsumerFreshness.java, kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/FreshnessTracker.java
We already track the issues via metrics, so the logging does not need to be quite so
verbose - listing every single topic/partition that can have a common error. This
can become particularly verbose when dealing with hundreds of consumers. Instead
this turns down the log levels so real errors can be more easily seen or are
summarized across all partitions (i.e. no partition has an end offset for the
consumer group, rather than listing potentially thousands of partitions).
=> Reduce logging verbosity for some common messages

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/Burrow.java, kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/ConsumerFreshness.java, kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/FreshnessTracker.java, kafka_consumer_freshness_tracker/src/test/java/com/tesla/data/consumer/freshness/BurrowTest.java, kafka_consumer_freshness_tracker/src/test/java/com/tesla/data/consumer/freshness/ConsumerFreshnessTest.java
Freshness tracker previously had errors like:
```
2021-03-24 17:38:17 ERROR [main] c.t.d.c.f.ConsumerFreshness:159 - Failed to read from burrow
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: (okio.RealBufferedSource$1); line: 1, column: 2]
at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561)
```
Which made it hard to debug what calls were actually failing
when connecting to burrow. At the same time, we occasionally fail
to load the status …
=> Better error cause information when failing to reach burrow or kafka

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/FreshnessTracker.java, kafka_consumer_freshness_tracker/src/test/java/com/tesla/data/consumer/freshness/BUILD, kafka_consumer_freshness_tracker/src/test/java/com/tesla/data/consumer/freshness/ConsumerFreshnessTest.java, kafka_consumer_freshness_tracker/src/test/resources/BUILD, kafka_consumer_freshness_tracker/src/test/resources/logback-test.xml
Adds more realistic test scenarios for existing tests (using a real threadpool and
mocking the Kafka interaction in the tracker), as well as explicitly covering the
various failure cases and how we handle them.
Also reverts the catching of KafkaConsumer exceptions in the FreshnessTracker, which
is how what would populate the per-consumer error metric.
=> Updating freshness tests to cover explicit failure/access handling

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/ConsumerFreshness.java, kafka_consumer_freshness_tracker/src/test/java/com/tesla/data/consumer/freshness/ConsumerFreshnessTest.java
This helps isolate the logic and error handling as the first
step to providing a clearer success/fail indicator per cluster.
Each cluster a single measurement that is waited upon (Future.get)
in the run loop. Each cluster Future waits on the completion of
each of the consumers in that cluster (itself a Future). Each
consumer Future is waiting on the completion of the FreshnessTracker
work for each partition.
That is, cluster = sum(consumer), consumer = sum(partitions).
Changes the behavior slightly for interruptions - they no longer
cause the burrowClustersConsumersReadFailed metric to increment,
which makes sense as that is not actually what failed (its actually
the interruption while waiting for an available KafkaConsumer).
Includes small tweaks to the tests as we use the executor pool …
=> Extract per-cluster and group freshness measurement

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/Burrow.java, kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/ConsumerFreshness.java
Sometimes in the logs we would see things like:
```
Jul 12, 2021 4:32:33 PM okhttp3.internal.platform.Platform log
ARNING: A connection to https://burrow.url/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jul 12, 2021 4:32:33 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://burrow.url/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jul 12, 2021 4:32:33 PM okhttp3.internal.platform.Platform log
```
which goes back to the burrow client not properly closing the
OkHttp …
=> Close OkHttp responses when no longer used in freshness tracker

kafka_certificates/src/main/java/com/tesla/data/certificates/keystore/PasswordGenerator.java, kafka_certificates/src/test/java/com/tesla/data/certificates/keystore/PasswordGeneratorTest.java
Ends up not playing nice when loading into strings in Java as they need to
be escaped. There are plenty of other 'good' special characters left to use,
so not a big risk to remove these in terms of randomness.
Test needs to be fixed because the range of characters to pick from is different,
leading to different items being selected from the list.
=> Password generator should not include slashes

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/FreshnessMetrics.java, kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/FreshnessTracker.java, kafka_consumer_freshness_tracker/src/test/java/com/tesla/data/consumer/freshness/FreshnessTrackerTest.java
Freshness tracker uses kafka record timestamp to determine
when the event may have entered our system. This timestamp can
be set in two ways
(a) A producer can set it, in which case the timestamp type is createtime
(b) Broker can set it, in which case the timestamp type is logappendtime
An edge case for freshness tracker is when producer sets the timestamp and
producer's clock is out of sync, in such case, freshness tracker will be
mislead into detecting a lag since it uses current system time (tracker's).
This change adds a new metric to track timestamp types. It doesn't do much
to avoid the false detection, but provides visibility to debug the issue further.
=> Add a metric to track kafka record timestamp type

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/Burrow.java, kafka_consumer_freshness_tracker/src/test/java/com/tesla/data/consumer/freshness/BurrowTest.java
Noticed when testing in staging that contrary to the Burrow [API documentation](https://github.com/linkedin/Burrow/wiki/http-request-kafka-cluster-detail), the response to a cluster detail call does not contain a `cluster` object containing a `module` object but rather, the `module` object is at the top-level.
This PR fixes the response parsing logic (and associated testing) to reflect this.
=> Fix parsing of Burrow get cluster detail response

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/ConsumerFreshness.java, kafka_consumer_freshness_tracker/src/test/java/com/tesla/data/consumer/freshness/ConsumerFreshnessTest.java
Across all the partitions for all topics for all consumers for a given
cluster, if we succeed at reading the freshness for at least one of
the consumers then the cluster freshness succeeds. Without this, if
none the consumers could be evaluated successfully then the cluster
would still be marked successful, but that often indicated an
incorrectly configured cluster. However, if we are able to read even
a single partition, then we can reach the cluster. Maybe its a transient
so we should be allowed a next round to try to get more successes.
Addresses #51
=> Cluster freshness should fail if no single partition succeeds

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/Burrow.java, kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/ConsumerFreshness.java, kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/FreshnessTracker.java
For burrow 404 errors, we avoid dumping the entire stack trace, but instead just log the exception message and move along. This dramatically cuts down log verbosity during normal operations, allowing the operator to see 'real' errors.
For when things get wonky, we need a way to see what the freshness tracker is using to calculate freshness - the current consumer state and the 'next' record against which freshness is calculated. Putting this at DEBUG lets us see what is happening, albeit with high degree of verbosity (most folks should not run at DEBUG normally though, this is just for debugging persistent tracker issues).
Addresses #59
=> Improve freshness verbosity

kafka_consumer_freshness_tracker/src/main/java/com/tesla/data/consumer/freshness/Burrow.java
That is, requests that complete but have a non-200 REST response code
are not logged at ERROR along with a stack trace. We already log the
error in the caller (ConsumerFreshness) and these burrow errors are
common enough and failed REST responses dont need full stack traces
to determine the eerror - in fact, the stack trace can often just add
noise to the log.
Example log messages + stack trace that we are trying to avoid:
```
2022-07-10 06:37:31 ERROR [main] c.t.d.c.f.Burrow:101 - Failed to complete request:Response{protocol=http/1.1, code=404, message=Not Found, url=http://burrow.cloud/v3/kafka/my-kafka/consumer/example_consumer/lag}
com.tesla.data.consumer.freshness.Burrow$UnsuccessfulResponseException: Response was not successful: Response{protocol=http/1.1, code=404, message=Not …
```
=> Burrow should not log unsuccessful request stack traces

kafka_roller/README.md, kafka_roller/kafka_roller/tasks.py
There are times we need to use a different command than `service kafka start` such as `reboot` or some command that manipulate the VM. This feature allows to specify this behavior instead of using the default service start.
=> Support customized command start-cmd for service start with kafka_roller.

.github/workflows/ci.yml, README.md
Note that this JDK/JRE on host is only used for running Bazel itself, not for building or testing code. The JDK/JRE used for building and testing is hermetically fetched by Bazel. Mention reliance on Java 17 in the project README.
=> Update Java version used by CI to 17

kafka_topic_enforcer/README.md
This logic has been there but is never documented. Let's mention it in the documentation so that it's known to our users.
=> Document the internal topic logic for topic enforcer.

kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/DumpCommand.java, kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/TopicEnforcer.java, kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/TopicService.java, kafka_topic_enforcer/src/main/java/com/tesla/data/topic/enforcer/TopicServiceImpl.java, kafka_topic_enforcer/src/test/java/com/tesla/data/topic/enforcer/TopicEnforcerTest.java, kafka_topic_enforcer/src/test/java/com/tesla/data/topic/enforcer/TopicServiceImplTest.java
Topic Enforcer lists existing topics with an optional filter to exclude internal topics from enforcement. It was intended to be a switch to allow including internal topics in the results. However, we have never included internal topics for the enforcer, and the current listing code does not work for that logic either -- even if we include internal topics in the Kafka admin client call, the internal topics are still filtered out at the step when we returns.
Given we are not using this include-internal logic, let's just remove it and clean up.
=> Clean up dead code in topic enforcer around listing existing topics.

kafka_quota_enforcer/src/main/java/com/tesla/data/quota/enforcer/ConfiguredQuota.java, kafka_quota_enforcer/src/main/java/com/tesla/data/quota/enforcer/QuotaService.java, kafka_quota_enforcer/src/test/java/com/tesla/data/quota/enforcer/BUILD, kafka_quota_enforcer/src/test/java/com/tesla/data/quota/enforcer/ConfiguredQuotaTest.java, kafka_quota_enforcer/src/test/java/com/tesla/data/quota/enforcer/QuotaEnforcerTest.java, kafka_quota_enforcer/src/test/java/com/tesla/data/quota/enforcer/QuotaServiceTest.java
This is to be consistent with Kafka's settings. Some tests are explicitly using integers in Kafka config to test the backward compatibility.
Note that this change is backward compatible. However, this commit is NOT rollback-safe, as new quota values will be set with decimals such as "10.0" in ZooKeeper even if the quota is set as integers in the config file, and if we rollback to older version of enforcer, it will fail at these decimal numbers.
=> Use double instead of integers for Kafka quota values.

kafka_quota_enforcer/src/main/java/com/tesla/data/quota/enforcer/AdminClientQuotaService.java, kafka_quota_enforcer/src/main/java/com/tesla/data/quota/enforcer/BUILD, kafka_quota_enforcer/src/main/java/com/tesla/data/quota/enforcer/ConfiguredQuota.java, kafka_quota_enforcer/src/test/java/com/tesla/data/quota/enforcer/AdminClientQuotaServiceTest.java, kafka_quota_enforcer/src/test/java/com/tesla/data/quota/enforcer/BUILD
We are implementing a Quota Service that does not rely on ZooKeeper following Kafka's documentation that can be found at https://kafka.apache.org/28/javadoc/org/apache/kafka/clients/admin/Admin.html. Unit tests are also included for this newly created Quota Service.
Our intention is to update and replace the current ZooKeeper based Quota Service to resolve #55. For now, we are only adding the new implementation without using it in the enforcer to avoid breaking existing use cases, while we are still adding new features.
=> Implement Kafka Admin Client based Quota Service.

kafka_enforcer_common/src/main/java/com/tesla/data/enforcer/Enforcer.java
The safety check would crash the enforcer, and we should log the expected deletions first to help debugging.
We also switch to return-early pattern for create and delete enforcer functions.
=> Kafka enforcer to log to-be deleted resources before safety check.
